version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: egghead_postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d